baseurl = "https://bloggerbust.ca/"
title = "Blogger Bust"
copyright = "Copyright (c) 2018, all rights reserved."
languageCode = "en-CA"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"
enableGitInfo = true

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

# [[menu.main]]
#   name = "Posts"
#   weight = -120
#   identifier = "post"
#   url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[author]
  name = "Trevor Wilson"

[params.meta]
  keywords = ["programming", "coding", "infosec", "cybersecurity", "webextensions", "blog", "blogger bust"]
  description = "a place for me to bust out a blog on programming, infosec, emacs and things that interest me."

[params]
  email = "trevor.wilson@bloggerbust.ca"
  github = "bloggerbust"

[params.colors]
  background = "#26282A"
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
