#+TITLE: About
#+author: Trevor Wilson
#+email: trevor.wilson@bloggerbust.ca
#+DATE: 2018-06-07
#+menu: main

* About Me
  I am a software developer and independent contractor residing in Edmonton Alberta, Canada. I have been developing software professionally since 2001 and graduated from the [[https://www.ualberta.ca][University of Alberta]] in 2005 with a major Mathematics and minor in computing science. One thing that I love about being an independent contractor is that over the years I have worked for lots of different companies which has allowed me to contribute to a large variety of exciting projects written in plenty of different languages. I have had the pleasure of working with so many wonderful teams who's members have taught me a great deal.

* About This Blog
  This blog is not new. Previously it was hosted by WordPress, but then I discovered the wonderful world of static site generators such as [[https://jekyllrb.com][Jekyll]] and [[https://gohugo.io][Hugo]]. I loved the idea of blogging directly in [[http://orgmode.org][Emacs org-mode]] and managing my [[https://github.com/BloggerBust/bloggerbust.ca][blog in GitHub]]. I chose Hugo over Jekyll only because with Hugo I did not need to install Ruby which I have no other need for at the moment. I considered migrating my old blog from WordPress to Hugo, but in the end I decided to just start fresh.
  
  I intend to blog about Emacs, Linux, programming, infosec, robotics, side projects and teaching my children to code :-)

* My Interests
  - editor: [[https://www.gnu.org/software/emacs/][Emacs]]
  - Linux distro: [[https://gentoo.org/][Gentoo]]
  - windows manager: [[http://www.fvwm.org][fvwm]] (but I might change this soon to [[http://www.nognu.org/xwem/][xwebm]]
  - file system: [[http://zfsonlinux.org][Zfs on Linux]]
  - language: this is a tough one. I love so many languages :-). Since most of my professional life is immersed in .Net C# I will probably focus on exploring python, lisp, C/C++ and assembly throughout this blog
  - dev machine: Alienware 17 R4

* Blogs I enjoy reading
  - [[http://nullprogram.com][null program]]
  - [[https://jvns.ca][Julia Evans]]
